### ISSUE TITLE
No oidv6-class-descriptions.csv file in your code

### ISSUE THREAD

**Issue by MarkDeng1** [KAI-YUE/rog#1]
Hi author,

I tried to run your code, but there is no oidv6-class-descriptions.csv found in your repo. 

Thanks.

**Comment by KAI-YUE** [comment]
Hi,

Are you referring to this file: https://storage.googleapis.com/openimages/v6/oidv6-class-descriptions.csv?

**Comment by KAI-YUE** [comment]
Hi,

The file can be found here:  https://storage.googleapis.com/openimages/v6/oidv6-class-descriptions.csv
