### ISSUE TITLE
CIFAR10

### ISSUE THREAD

**Issue by HuitongJin** [KAI-YUE/rog#2]
Hello, if I want to use this algorithm on the CIFAR10 dataset, do the pre-training weights in model_zoos need to be adjusted? How to train the weights for CIFAR10? The files involved include: postmodel.pth, tresnet.pth, usrgan.pth etc.

**Comment by KAI-YUE** [comment]
I am not sure which resolution you want to preserve (128 or 32). You can align the labels of cifar-10 to Imagenet and give a try first.
